version: '3'
services:
  api:
    build: api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
